package com.softwinner.fireplayer.floatwindow;

public class FloatWindowFlags {
    public static final int FLAG_ADD_FUNCTIONALITY_ALL_DISABLE;
    public static final int FLAG_ADD_FUNCTIONALITY_DROP_DOWN_DISABLE;
    public static final int FLAG_ADD_FUNCTIONALITY_RESIZE_DISABLE;
    public static final int FLAG_BODY_MOVE_ENABLE;
    public static final int FLAG_DECORATION_CLOSE_DISABLE;
    public static final int FLAG_DECORATION_MOVE_DISABLE;
    public static final int FLAG_DECORATION_RESIZE_DISABLE;
    public static final int FLAG_DECORATION_SYSTEM;
    public static final int FLAG_FIX_COMPATIBILITY_ALL_DISABLE;
    public static final int FLAG_WINDOW_ASPECT_RATIO_ENABLE;
    public static final int FLAG_WINDOW_BRING_TO_FRONT_ON_TAP;
    public static final int FLAG_WINDOW_BRING_TO_FRONT_ON_TOUCH;
    public static final int FLAG_WINDOW_EDGE_LIMITS_ENABLE;
    public static final int FLAG_WINDOW_FOCUSABLE_DISABLE;
    public static final int FLAG_WINDOW_FOCUS_INDICATOR_DISABLE;
    public static final int FLAG_WINDOW_HIDE_ENABLE;
    public static final int FLAG_WINDOW_PINCH_RESIZE_ENABLE;
    private static int flag_bit;

    static {
        flag_bit = 0;
        int i = flag_bit;
        flag_bit = i + 1;
        FLAG_DECORATION_SYSTEM = 1 << i;
        int i2 = FLAG_DECORATION_SYSTEM;
        int i3 = flag_bit;
        flag_bit = i3 + 1;
        FLAG_DECORATION_CLOSE_DISABLE = i2 | (1 << i3);
        int i4 = FLAG_DECORATION_SYSTEM;
        int i5 = flag_bit;
        flag_bit = i5 + 1;
        FLAG_DECORATION_RESIZE_DISABLE = i4 | (1 << i5);
        int i6 = FLAG_DECORATION_SYSTEM;
        int i7 = flag_bit;
        flag_bit = i7 + 1;
        FLAG_DECORATION_MOVE_DISABLE = i6 | (1 << i7);
        int i8 = flag_bit;
        flag_bit = i8 + 1;
        FLAG_BODY_MOVE_ENABLE = 1 << i8;
        int i9 = flag_bit;
        flag_bit = i9 + 1;
        FLAG_WINDOW_HIDE_ENABLE = 1 << i9;
        int i10 = flag_bit;
        flag_bit = i10 + 1;
        FLAG_WINDOW_BRING_TO_FRONT_ON_TOUCH = 1 << i10;
        int i11 = flag_bit;
        flag_bit = i11 + 1;
        FLAG_WINDOW_BRING_TO_FRONT_ON_TAP = 1 << i11;
        int i12 = flag_bit;
        flag_bit = i12 + 1;
        FLAG_WINDOW_EDGE_LIMITS_ENABLE = 1 << i12;
        int i13 = flag_bit;
        flag_bit = i13 + 1;
        FLAG_WINDOW_ASPECT_RATIO_ENABLE = 1 << i13;
        int i14 = flag_bit;
        flag_bit = i14 + 1;
        FLAG_WINDOW_PINCH_RESIZE_ENABLE = 1 << i14;
        int i15 = flag_bit;
        flag_bit = i15 + 1;
        FLAG_WINDOW_FOCUSABLE_DISABLE = 1 << i15;
        int i16 = flag_bit;
        flag_bit = i16 + 1;
        FLAG_WINDOW_FOCUS_INDICATOR_DISABLE = 1 << i16;
        int i17 = flag_bit;
        flag_bit = i17 + 1;
        FLAG_FIX_COMPATIBILITY_ALL_DISABLE = 1 << i17;
        int i18 = flag_bit;
        flag_bit = i18 + 1;
        FLAG_ADD_FUNCTIONALITY_ALL_DISABLE = 1 << i18;
        int i19 = flag_bit;
        flag_bit = i19 + 1;
        FLAG_ADD_FUNCTIONALITY_RESIZE_DISABLE = 1 << i19;
        int i20 = flag_bit;
        flag_bit = i20 + 1;
        FLAG_ADD_FUNCTIONALITY_DROP_DOWN_DISABLE = 1 << i20;
    }
}
